# Generated by Django 4.2.1 on 2023-05-19 18:07

from django.db import migrations, models
import django.utils.timezone
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_subject_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, validators=[tasks.models.fecha_en_futuro], verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Prioridad baja'), ('N', 'Prioridad normal'), ('H', 'Prioridad alta')], default='N', max_length=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
